require(nCov2019)
require(chinamap)
require(ggplot2)
plot(get_nCov2019(), region="china", chinamap=get_map_china(), continuous_scale=FALSE,palette="Blues")

plot(load_nCov2019(), region='china', chinamap=get_map_china(), date='2020-01-21')
+theme_bw()+theme(panel.grid.major=element_line(colour=NA))
plot(load_nCov2019(), region='china', chinamap=get_map_china(), date='2020-01-26')+theme_bw()+theme(panel.grid.major=element_line(colour=NA))
plot(load_nCov2019(), region='china', chinamap=get_map_china(), date='2020-02-03')+theme_bw()+theme(panel.grid.major=element_line(colour=NA))
plot(load_nCov2019(), region='china', chinamap=get_map_china(), date='2020-02-18')+theme_bw()+theme(panel.grid.major=element_line(colour=NA))
plot(load_nCov2019(), region='china', chinamap=get_map_china(), date='2020-03-01')+theme_bw()+theme(panel.grid.major=element_line(colour=NA))
plot(load_nCov2019(), region='china', chinamap=get_map_china(), date='2020-07-27')+theme_bw()+theme(panel.grid.major=element_line(colour=NA))

m <- sf::st_read("china-city-map/市界.shp")
plot(load_nCov2019(), region='湖北', chinamap=m, date='2020-01-27')+theme_bw()+theme(panel.grid.major=element_line(colour=NA))
plot(load_nCov2019(), region='湖北', chinamap=m, date='2020-04-08')+theme_bw()+theme(panel.grid.major=element_line(colour=NA))
plot(load_nCov2019(), region='湖北', chinamap=m, date='2020-07-27')+theme_bw()+theme(panel.grid.major=element_line(colour=NA))
